import java.util.List;

public class ExercicioTecProg01 {
    public static void main(String[] args) {
        Pessoa pessoa = new PessoaImpl2("Jailtom", "11-01-85");
        List<Pessoa> pessoas = List.of(
                new PessoaImpl2("Diego Márcio Pedro da Rocha", "10-07-87"),
                new PessoaImpl2("Edson Pietro Moraes", "01-02-42"),
                new PessoaImpl2("Caroline Natália Débora da Mata", "16-01-64"),
                new PessoaImpl2("Renato Pedro Paulo Moura", "21-03-74"),
                new PessoaImpl2("Francisca Raquel Elaine Caldeira", "02-07-81"),
                new PessoaImpl2("Hugo Anthony da Costa", "27-05-95"),
                new PessoaImpl2("Bernardo Carlos Eduardo Ricardo Freitas", "07-04-87"),
                new PessoaImpl2("Mariane Heloise Fabiana Rocha", "18-02-04"),
                new PessoaImpl2("Juan André Tiago da Cunha", "23-02-43"),
                new PessoaImpl2("Gabriel Diogo Pires", "02-06-68"),
                new PessoaImpl2("Gustavo Alexandre Barbosa", "01-06-73"),
                new PessoaImpl2("Danilo Paulo de Paula", "08-05-88"),
                new PessoaImpl2("Isadora Ayla Milena Costa", "17-03-51"),
                new PessoaImpl2("Mário Raul Barros", "07-02-98"),
                new PessoaImpl2("Nelson Tomás Nogueira", "12-06-84"),
                new PessoaImpl2("Gabriela Priscila Mariane Drumond", "10-05-48"),
                new PessoaImpl2("Marcos Vinicius Elias Severino Carvalho", "15-01-46"),
                new PessoaImpl2("Bento Roberto Teixeira", "25-01-46"),
                new PessoaImpl2("Arthur Murilo Nelson Rodrigues", "12-07-80"),
                new PessoaImpl2("Teresinha Ana Natália dos Santos", "07-01-02"),
                new PessoaImpl2("Aline Stefany Moreira", "01-06-94"),
                new PessoaImpl2("Filipe Daniel Raimundo Pinto", "02-02-82"),
                new PessoaImpl2("Agatha Fátima Laura Peixoto", "19-03-83"),
                new PessoaImpl2("Vitória Cristiane Valentina Alves", "01-05-76"),
                new PessoaImpl2("Elza Sebastiana Santos", "09-04-47"),
                new PessoaImpl2("Isabella Cláudia Elza Almada", "01-05-62"),
                new PessoaImpl2("Kevin Theo Nascimento", "11-05-45"),
                new PessoaImpl2("Mário Renato Monteiro", "03-01-04"),
                new PessoaImpl2("Emily Sarah Antônia Fogaça", "18-01-88"),
                new PessoaImpl2("Simone Joana Nunes", "01-01-61"),
                new PessoaImpl2("Marcos Vinicius Theo dos Santos", "12-04-81"),
                new PessoaImpl2("Thomas Ruan Drumond", "01-01-04"),
                new PessoaImpl2("Manuel Pietro Brito", "13-03-79"),
                new PessoaImpl2("Elaine Fernanda Luiza Cardoso", "23-05-56"),
                new PessoaImpl2("Benício Otávio Nogueira", "04-05-49"),
                new PessoaImpl2("João Marcos Fernandes", "08-05-02"),
                new PessoaImpl2("Maria Fabiana Lima", "06-07-60"),
                new PessoaImpl2("Tânia Melissa Kamilly Dias", "10-03-88"),
                new PessoaImpl2("Cauê Severino Silveira", "15-02-49"),
                new PessoaImpl2("Diogo Luís Barros", "16-02-63"),
                new PessoaImpl2("Márcio Sérgio Teixeira", "09-05-89"),
                new PessoaImpl2("Juliana Mariana Bernardes", "07-03-96"),
                new PessoaImpl2("Fabiana Maria Isabella Caldeira", "20-01-69"),
                new PessoaImpl2("Vicente Luiz Kauê da Conceição", "10-07-90"),
                new PessoaImpl2("Mirella Letícia Josefa Gonçalves", "07-07-72"),
                new PessoaImpl2("Roberto Enzo Galvão", "24-01-74"),
                new PessoaImpl2("Tereza Elaine Esther da Paz", "08-03-65"),
                new PessoaImpl2("Louise Vitória Souza", "25-01-52"),
                new PessoaImpl2("Ricardo Benício Ribeiro", "21-03-73"),
                new PessoaImpl2("Rafaela Vera Raquel Farias", "14-07-78"),
                new PessoaImpl2("Breno Sebastião Lucca Moura", "21-06-47"),
                new PessoaImpl2("Pedro Felipe Alves", "12-04-67"),
                new PessoaImpl2("Kaique Roberto Assis", "14-07-92"),
                new PessoaImpl2("Elaine Sônia Vieira", "17-01-52"),
                new PessoaImpl2("Lavínia Lúcia Duarte", "08-02-47"),
                new PessoaImpl2("Danilo Caio Benício Martins", "09-07-56"),
                new PessoaImpl2("Matheus Thiago Juan da Luz", "03-06-88"),
                new PessoaImpl2("Cláudia Camila Rodrigues", "16-01-62"),
                new PessoaImpl2("Davi Renato Barbosa", "26-01-90"),
                new PessoaImpl2("Isaac Marcos Freitas", "07-06-00"),
                new PessoaImpl2("Pedro Marcos Augusto Almada", "15-06-57"),
                new PessoaImpl2("Giovana Isabel Renata Santos", "18-01-52"),
                new PessoaImpl2("Tatiane Luciana da Cunha", "08-07-00"),
                new PessoaImpl2("Amanda Mirella Eliane Brito", "27-05-02"),
                new PessoaImpl2("Fabiana Marcela Emanuelly da Luz", "02-02-02"),
                new PessoaImpl2("Rosa Nair Lúcia Moura", "24-02-02"),
                new PessoaImpl2("Tatiane Francisca Antonella Fogaça", "02-04-54"),
                new PessoaImpl2("Amanda Sueli dos Santos", "14-07-48"),
                new PessoaImpl2("Breno Caio Drumond", "03-03-04"),
                new PessoaImpl2("Cauê Daniel Lima", "04-03-90"),
                new PessoaImpl2("Fátima Lúcia Barbosa", "19-04-64"),
                new PessoaImpl2("Olivia Luna Aparício", "24-04-03"),
                new PessoaImpl2("Tânia Luciana Vitória da Mota", "14-07-51"),
                new PessoaImpl2("Martin Lorenzo Jesus", "09-06-92"),
                new PessoaImpl2("Sabrina Ayla Maya Baptista", "18-04-82"),
                new PessoaImpl2("Stefany Andrea Silveira", "16-04-72"),
                new PessoaImpl2("Olivia Analu Milena da Mata", "24-01-80"),
                new PessoaImpl2("Carlos Luiz Ian Lopes", "27-05-65"),
                new PessoaImpl2("Betina Natália Betina Nogueira", "08-07-50"),
                new PessoaImpl2("Carla Márcia Juliana Nunes", "20-03-51"),
                new PessoaImpl2("Silvana Lavínia Fátima Corte Real", "12-03-45"),
                new PessoaImpl2("Betina Josefa Ramos", "02-04-74"),
                new PessoaImpl2("Raimunda Vera Moraes", "22-03-93"),
                new PessoaImpl2("Calebe Edson André Gomes", "02-07-85"),
                new PessoaImpl2("Enrico Ryan Marcos Vinicius Pinto", "16-01-90"),
                new PessoaImpl2("Esther Elza Silvana Caldeira", "23-03-68"),
                new PessoaImpl2("André César Mário Carvalho", "04-03-89"),
                new PessoaImpl2("Renan Rodrigo Bernardes", "08-04-73"),
                new PessoaImpl2("Samuel Kevin Francisco Pereira", "02-02-61"),
                new PessoaImpl2("Nathan Luan César Castro", "23-02-73"),
                new PessoaImpl2("Débora Jaqueline Nunes", "23-01-77"),
                new PessoaImpl2("Amanda Carolina Gabrielly Caldeira", "04-02-69"),
                new PessoaImpl2("Sophia Antonella Figueiredo", "26-04-82"),
                new PessoaImpl2("Daiane Aparecida Barbosa", "19-04-50"),
                new PessoaImpl2("Osvaldo Diego Ramos", "08-04-53"),
                new PessoaImpl2("Cauã Nelson Lopes", "05-05-00"),
                new PessoaImpl2("Mirella Giovanna Pires", "18-06-66"),
                new PessoaImpl2("Francisca Sophie Luna Santos", "09-01-01"),
                new PessoaImpl2("Isabela Sebastiana Rezende", "09-03-63"),
                new PessoaImpl2("Silvana Alícia Martins", "17-03-65"),
                new PessoaImpl2("Elaine Elaine Ferreira", "16-02-01"),
                new PessoaImpl2("Jennifer Agatha Bernardes", "16-04-56"),
                new PessoaImpl2("Luiz Luís Arthur Monteiro", "07-05-54"),
                new PessoaImpl2("Joaquim Renato Benício da Paz", "09-01-80"),
                new PessoaImpl2("Débora Lívia da Mata", "14-02-75"),
                new PessoaImpl2("Mariah Carolina Benedita Assunção", "27-03-86"),
                new PessoaImpl2("Fábio Emanuel Vicente da Cruz", "14-04-95"),
                new PessoaImpl2("Daniela Luiza Marina Moreira", "24-01-58"),
                new PessoaImpl2("Márcio Joaquim Fábio dos Santos", "22-06-50"),
                new PessoaImpl2("Erick Hugo Gomes", "18-01-86"),
                new PessoaImpl2("Mariana Agatha Emanuelly Sales", "06-04-68"),
                new PessoaImpl2("Maitê Renata Marina da Silva", "09-07-94"),
                new PessoaImpl2("Cláudio Guilherme Caio Pereira", "06-05-85"),
                new PessoaImpl2("Patrícia Hadassa Louise Carvalho", "15-05-04"),
                new PessoaImpl2("Maitê Andreia Elisa Aparício", "14-06-55"),
                new PessoaImpl2("Fernanda Adriana Ester Ribeiro", "12-06-92"),
                new PessoaImpl2("Sandra Luana Silveira", "19-06-92"),
                new PessoaImpl2("Augusto Joaquim Ian Porto", "02-01-64"),
                new PessoaImpl2("Eloá Sarah das Neves", "19-04-69"),
                new PessoaImpl2("Simone Maria Fernandes", "17-04-73")
                );
        pessoas.forEach(pessoa1 -> System.out.println(pessoa1.getIdade()));
    }
}
